<?php

putenv('DISPLAY_ERRORS_DETAILS=' . true);

putenv('DB_EVERDADE_MYSQL_HOST=127.0.0.1');
putenv('DB_EVERDADE_MYSQL_DBNAME=bd_everdade');
putenv('DB_EVERDADE_MYSQL_USER=root');
putenv('DB_EVERDADE_MYSQL_PASSWORD=');
putenv('DB_EVERDADE_MYSQL_PORT=3306');